databases:
  - name: horarabo_DB
    databaseName: horarabo_db
    user: horarabo
    region: singapore

services:
  - type: web
    name: horarabo
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: horarabo_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false